# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rcspy_Exportdialog.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.WindowModal)
        Dialog.setEnabled(True)
        Dialog.resize(530, 483)
        Dialog.setMinimumSize(QtCore.QSize(530, 483))
        Dialog.setMaximumSize(QtCore.QSize(530, 483))
        self.File_list = QtWidgets.QListWidget(Dialog)
        self.File_list.setGeometry(QtCore.QRect(10, 40, 231, 331))
        self.File_list.setObjectName("File_list")
        self.channel_list = QtWidgets.QListWidget(Dialog)
        self.channel_list.setGeometry(QtCore.QRect(250, 40, 121, 311))
        self.channel_list.setObjectName("channel_list")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(390, 70, 91, 181))
        self.groupBox.setObjectName("groupBox")
        self.radioSEED = QtWidgets.QRadioButton(self.groupBox)
        self.radioSEED.setGeometry(QtCore.QRect(10, 150, 89, 16))
        self.radioSEED.setObjectName("radioSEED")
        self.radioSAC = QtWidgets.QRadioButton(self.groupBox)
        self.radioSAC.setGeometry(QtCore.QRect(10, 110, 89, 16))
        self.radioSAC.setObjectName("radioSAC")
        self.radioMSEED = QtWidgets.QRadioButton(self.groupBox)
        self.radioMSEED.setGeometry(QtCore.QRect(10, 70, 89, 16))
        self.radioMSEED.setObjectName("radioMSEED")
        self.radioASCII = QtWidgets.QRadioButton(self.groupBox)
        self.radioASCII.setGeometry(QtCore.QRect(10, 30, 89, 16))
        self.radioASCII.setObjectName("radioASCII")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(380, 270, 141, 101))
        self.groupBox_2.setObjectName("groupBox_2")
        self.starttime_edit = QtWidgets.QLineEdit(self.groupBox_2)
        self.starttime_edit.setGeometry(QtCore.QRect(50, 30, 81, 20))
        self.starttime_edit.setObjectName("starttime_edit")
        self.endtimee_edit = QtWidgets.QLineEdit(self.groupBox_2)
        self.endtimee_edit.setGeometry(QtCore.QRect(50, 60, 81, 20))
        self.endtimee_edit.setObjectName("endtimee_edit")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(10, 30, 31, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 31, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 20, 54, 12))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(250, 20, 54, 12))
        self.label_4.setObjectName("label_4")
        self.allchannel_checkbox = QtWidgets.QCheckBox(Dialog)
        self.allchannel_checkbox.setGeometry(QtCore.QRect(260, 360, 91, 16))
        self.allchannel_checkbox.setObjectName("allchannel_checkbox")
        self.btn_set_folder = QtWidgets.QPushButton(Dialog)
        self.btn_set_folder.setGeometry(QtCore.QRect(10, 380, 75, 23))
        self.btn_set_folder.setObjectName("btn_set_folder")
        self.Exfolder_edit = QtWidgets.QLineEdit(Dialog)
        self.Exfolder_edit.setGeometry(QtCore.QRect(10, 410, 511, 20))
        self.Exfolder_edit.setReadOnly(True)
        self.Exfolder_edit.setObjectName("Exfolder_edit")
        self.btnOK = QtWidgets.QPushButton(Dialog)
        self.btnOK.setGeometry(QtCore.QRect(140, 450, 75, 23))
        self.btnOK.setObjectName("btnOK")
        self.btn_Cancel = QtWidgets.QPushButton(Dialog)
        self.btn_Cancel.setGeometry(QtCore.QRect(300, 450, 75, 23))
        self.btn_Cancel.setObjectName("btn_Cancel")
        self.single_channel_checkbox = QtWidgets.QCheckBox(Dialog)
        self.single_channel_checkbox.setGeometry(QtCore.QRect(260, 380, 121, 16))
        self.single_channel_checkbox.setObjectName("single_channel_checkbox")
        self.groupBox.raise_()
        self.File_list.raise_()
        self.channel_list.raise_()
        self.groupBox_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.allchannel_checkbox.raise_()
        self.btn_set_folder.raise_()
        self.Exfolder_edit.raise_()
        self.btnOK.raise_()
        self.btn_Cancel.raise_()
        self.single_channel_checkbox.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "导出"))
        self.groupBox.setTitle(_translate("Dialog", "文件格式"))
        self.radioSEED.setText(_translate("Dialog", "SEED"))
        self.radioSAC.setText(_translate("Dialog", "SAC"))
        self.radioMSEED.setText(_translate("Dialog", "miniSEED"))
        self.radioASCII.setText(_translate("Dialog", "ASCII"))
        self.groupBox_2.setTitle(_translate("Dialog", "时间长度"))
        self.label.setText(_translate("Dialog", "开始："))
        self.label_2.setText(_translate("Dialog", "结束："))
        self.label_3.setText(_translate("Dialog", "文件名"))
        self.label_4.setText(_translate("Dialog", "通道"))
        self.allchannel_checkbox.setText(_translate("Dialog", "所有通道"))
        self.btn_set_folder.setText(_translate("Dialog", "选择文件夹"))
        self.btnOK.setText(_translate("Dialog", "导出"))
        self.btn_Cancel.setText(_translate("Dialog", "取消"))
        self.single_channel_checkbox.setText(_translate("Dialog", "一个通道一个文件"))

