# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rcspy_Taupdialog.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.WindowModal)
        Dialog.setEnabled(True)
        Dialog.resize(560, 500)
        Dialog.setMinimumSize(QtCore.QSize(560, 500))
        Dialog.setMaximumSize(QtCore.QSize(560, 550))
        self.File_list = QtWidgets.QListWidget(Dialog)
        self.File_list.setGeometry(QtCore.QRect(10, 30, 191, 431))
        self.File_list.setObjectName("File_list")
        self.channel_list = QtWidgets.QListWidget(Dialog)
        self.channel_list.setGeometry(QtCore.QRect(210, 30, 121, 431))
        self.channel_list.setObjectName("channel_list")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 54, 12))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(210, 10, 54, 12))
        self.label_4.setObjectName("label_4")
        self.btnOK = QtWidgets.QPushButton(Dialog)
        self.btnOK.setGeometry(QtCore.QRect(360, 470, 70, 22))
        self.btnOK.setObjectName("btnOK")
        self.btn_Cancel = QtWidgets.QPushButton(Dialog)
        self.btn_Cancel.setGeometry(QtCore.QRect(460, 470, 70, 22))
        self.btn_Cancel.setObjectName("btn_Cancel")
        self.btn_Event = QtWidgets.QPushButton(Dialog)
        self.btn_Event.setGeometry(QtCore.QRect(340, 10, 111, 26))
        self.btn_Event.setObjectName("btn_Event")
        self.eventdisplayer = QtWidgets.QLineEdit(Dialog)
        self.eventdisplayer.setGeometry(QtCore.QRect(340, 40, 211, 27))
        self.eventdisplayer.setReadOnly(True)
        self.eventdisplayer.setObjectName("eventdisplayer")
        self.btn_Inv = QtWidgets.QPushButton(Dialog)
        self.btn_Inv.setGeometry(QtCore.QRect(340, 70, 111, 26))
        self.btn_Inv.setObjectName("btn_Inv")
        self.invdisplayer = QtWidgets.QLineEdit(Dialog)
        self.invdisplayer.setGeometry(QtCore.QRect(340, 100, 211, 27))
        self.invdisplayer.setReadOnly(True)
        self.invdisplayer.setObjectName("invdisplayer")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(340, 130, 211, 91))
        self.groupBox.setObjectName("groupBox")
        self.Pgchenkbox = QtWidgets.QCheckBox(self.groupBox)
        self.Pgchenkbox.setGeometry(QtCore.QRect(40, 30, 51, 22))
        self.Pgchenkbox.setChecked(True)
        self.Pgchenkbox.setObjectName("Pgchenkbox")
        self.Pnchenkbox = QtWidgets.QCheckBox(self.groupBox)
        self.Pnchenkbox.setGeometry(QtCore.QRect(40, 60, 51, 22))
        self.Pnchenkbox.setChecked(True)
        self.Pnchenkbox.setObjectName("Pnchenkbox")
        self.Sgchenkbox = QtWidgets.QCheckBox(self.groupBox)
        self.Sgchenkbox.setGeometry(QtCore.QRect(120, 30, 51, 22))
        self.Sgchenkbox.setChecked(True)
        self.Sgchenkbox.setObjectName("Sgchenkbox")
        self.Snchenkbox = QtWidgets.QCheckBox(self.groupBox)
        self.Snchenkbox.setGeometry(QtCore.QRect(120, 60, 51, 22))
        self.Snchenkbox.setChecked(True)
        self.Snchenkbox.setObjectName("Snchenkbox")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(340, 220, 211, 111))
        self.groupBox_2.setObjectName("groupBox_2")
        self.soulongti = QtWidgets.QLabel(self.groupBox_2)
        self.soulongti.setGeometry(QtCore.QRect(50, 30, 151, 17))
        self.soulongti.setText("")
        self.soulongti.setObjectName("soulongti")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(10, 30, 31, 17))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(10, 90, 31, 17))
        self.label_7.setObjectName("label_7")
        self.soudepth = QtWidgets.QLabel(self.groupBox_2)
        self.soudepth.setGeometry(QtCore.QRect(50, 90, 151, 17))
        self.soudepth.setText("")
        self.soudepth.setObjectName("soudepth")
        self.soulati = QtWidgets.QLabel(self.groupBox_2)
        self.soulati.setGeometry(QtCore.QRect(50, 60, 151, 17))
        self.soulati.setText("")
        self.soulati.setObjectName("soulati")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(10, 60, 31, 17))
        self.label_8.setObjectName("label_8")
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(340, 340, 211, 111))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setGeometry(QtCore.QRect(10, 30, 31, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 31, 17))
        self.label_2.setObjectName("label_2")
        self.stalongti = QtWidgets.QLabel(self.groupBox_3)
        self.stalongti.setGeometry(QtCore.QRect(50, 30, 151, 17))
        self.stalongti.setText("")
        self.stalongti.setObjectName("stalongti")
        self.stalati = QtWidgets.QLabel(self.groupBox_3)
        self.stalati.setGeometry(QtCore.QRect(50, 60, 151, 17))
        self.stalati.setText("")
        self.stalati.setObjectName("stalati")
        self.stadepth = QtWidgets.QLabel(self.groupBox_3)
        self.stadepth.setGeometry(QtCore.QRect(50, 90, 151, 17))
        self.stadepth.setText("")
        self.stadepth.setObjectName("stadepth")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(10, 90, 31, 17))
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "理论到时计算"))
        self.label_3.setText(_translate("Dialog", "文件名"))
        self.label_4.setText(_translate("Dialog", "通道"))
        self.btnOK.setText(_translate("Dialog", "确认"))
        self.btn_Cancel.setText(_translate("Dialog", "返回"))
        self.btn_Event.setText(_translate("Dialog", "指定事件文件"))
        self.btn_Inv.setText(_translate("Dialog", "指定Inventory"))
        self.groupBox.setTitle(_translate("Dialog", "震相"))
        self.Pgchenkbox.setText(_translate("Dialog", "Pg"))
        self.Pnchenkbox.setText(_translate("Dialog", "Pn"))
        self.Sgchenkbox.setText(_translate("Dialog", "Sg"))
        self.Snchenkbox.setText(_translate("Dialog", "Sn"))
        self.groupBox_2.setTitle(_translate("Dialog", "震源"))
        self.label_6.setText(_translate("Dialog", "经度"))
        self.label_7.setText(_translate("Dialog", "深度"))
        self.label_8.setText(_translate("Dialog", "纬度"))
        self.groupBox_3.setTitle(_translate("Dialog", "台站"))
        self.label.setText(_translate("Dialog", "经度"))
        self.label_2.setText(_translate("Dialog", "纬度"))
        self.label_5.setText(_translate("Dialog", "深度"))

