# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rcspy_Preprocessdialog.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.WindowModal)
        Dialog.setEnabled(True)
        Dialog.resize(560, 515)
        Dialog.setMinimumSize(QtCore.QSize(560, 500))
        Dialog.setMaximumSize(QtCore.QSize(560, 550))
        self.File_list = QtWidgets.QListWidget(Dialog)
        self.File_list.setGeometry(QtCore.QRect(10, 30, 191, 411))
        self.File_list.setObjectName("File_list")
        self.channel_list = QtWidgets.QListWidget(Dialog)
        self.channel_list.setGeometry(QtCore.QRect(210, 30, 121, 471))
        self.channel_list.setObjectName("channel_list")
        self.detrend_switch = QtWidgets.QGroupBox(Dialog)
        self.detrend_switch.setGeometry(QtCore.QRect(340, 30, 211, 45))
        self.detrend_switch.setCheckable(True)
        self.detrend_switch.setChecked(False)
        self.detrend_switch.setObjectName("detrend_switch")
        self.radioLinear = QtWidgets.QRadioButton(self.detrend_switch)
        self.radioLinear.setGeometry(QtCore.QRect(110, 24, 89, 21))
        self.radioLinear.setObjectName("radioLinear")
        self.radioConstant = QtWidgets.QRadioButton(self.detrend_switch)
        self.radioConstant.setGeometry(QtCore.QRect(10, 24, 89, 21))
        self.radioConstant.setChecked(True)
        self.radioConstant.setObjectName("radioConstant")
        self.bandpass_switch = QtWidgets.QGroupBox(Dialog)
        self.bandpass_switch.setGeometry(QtCore.QRect(340, 240, 211, 171))
        self.bandpass_switch.setCheckable(True)
        self.bandpass_switch.setChecked(False)
        self.bandpass_switch.setObjectName("bandpass_switch")
        self.fminSlider = QtWidgets.QSlider(self.bandpass_switch)
        self.fminSlider.setGeometry(QtCore.QRect(10, 80, 191, 22))
        self.fminSlider.setMaximum(1000)
        self.fminSlider.setProperty("value", 10)
        self.fminSlider.setOrientation(QtCore.Qt.Horizontal)
        self.fminSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.fminSlider.setTickInterval(100)
        self.fminSlider.setObjectName("fminSlider")
        self.fmaxSlider = QtWidgets.QSlider(self.bandpass_switch)
        self.fmaxSlider.setGeometry(QtCore.QRect(10, 110, 191, 22))
        self.fmaxSlider.setMaximum(1000)
        self.fmaxSlider.setProperty("value", 200)
        self.fmaxSlider.setOrientation(QtCore.Qt.Horizontal)
        self.fmaxSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.fmaxSlider.setTickInterval(100)
        self.fmaxSlider.setObjectName("fmaxSlider")
        self.fminspin = QtWidgets.QDoubleSpinBox(self.bandpass_switch)
        self.fminspin.setGeometry(QtCore.QRect(120, 20, 81, 22))
        self.fminspin.setSpecialValueText("")
        self.fminspin.setPrefix("")
        self.fminspin.setMaximum(100.0)
        self.fminspin.setProperty("value", 1.0)
        self.fminspin.setObjectName("fminspin")
        self.fmaxspin = QtWidgets.QDoubleSpinBox(self.bandpass_switch)
        self.fmaxspin.setGeometry(QtCore.QRect(120, 50, 81, 22))
        self.fmaxspin.setProperty("value", 20.0)
        self.fmaxspin.setObjectName("fmaxspin")
        self.label = QtWidgets.QLabel(self.bandpass_switch)
        self.label.setGeometry(QtCore.QRect(10, 20, 101, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.bandpass_switch)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 101, 21))
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.bandpass_switch)
        self.label_5.setGeometry(QtCore.QRect(10, 140, 54, 21))
        self.label_5.setObjectName("label_5")
        self.corners_spin = QtWidgets.QSpinBox(self.bandpass_switch)
        self.corners_spin.setGeometry(QtCore.QRect(70, 140, 41, 22))
        self.corners_spin.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.corners_spin.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.corners_spin.setMinimum(2)
        self.corners_spin.setMaximum(8)
        self.corners_spin.setProperty("value", 4)
        self.corners_spin.setObjectName("corners_spin")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 54, 12))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(210, 10, 54, 12))
        self.label_4.setObjectName("label_4")
        self.allchannel_checkbox = QtWidgets.QCheckBox(Dialog)
        self.allchannel_checkbox.setGeometry(QtCore.QRect(110, 450, 91, 21))
        self.allchannel_checkbox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.allchannel_checkbox.setObjectName("allchannel_checkbox")
        self.btnOK = QtWidgets.QPushButton(Dialog)
        self.btnOK.setGeometry(QtCore.QRect(20, 480, 70, 22))
        self.btnOK.setObjectName("btnOK")
        self.btn_Cancel = QtWidgets.QPushButton(Dialog)
        self.btn_Cancel.setGeometry(QtCore.QRect(120, 480, 70, 22))
        self.btn_Cancel.setObjectName("btn_Cancel")
        self.remove_response_switch = QtWidgets.QGroupBox(Dialog)
        self.remove_response_switch.setGeometry(QtCore.QRect(340, 80, 211, 161))
        self.remove_response_switch.setCheckable(True)
        self.remove_response_switch.setChecked(False)
        self.remove_response_switch.setObjectName("remove_response_switch")
        self.label_6 = QtWidgets.QLabel(self.remove_response_switch)
        self.label_6.setGeometry(QtCore.QRect(10, 24, 71, 21))
        self.label_6.setObjectName("label_6")
        self.water_level_spin = QtWidgets.QSpinBox(self.remove_response_switch)
        self.water_level_spin.setGeometry(QtCore.QRect(120, 24, 41, 21))
        self.water_level_spin.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.water_level_spin.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.water_level_spin.setMinimum(0)
        self.water_level_spin.setMaximum(100)
        self.water_level_spin.setProperty("value", 60)
        self.water_level_spin.setObjectName("water_level_spin")
        self.btn_setInv = QtWidgets.QPushButton(self.remove_response_switch)
        self.btn_setInv.setGeometry(QtCore.QRect(10, 130, 91, 23))
        self.btn_setInv.setObjectName("btn_setInv")
        self.pre_filt_switch = QtWidgets.QCheckBox(self.remove_response_switch)
        self.pre_filt_switch.setGeometry(QtCore.QRect(10, 50, 91, 16))
        self.pre_filt_switch.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pre_filt_switch.setObjectName("pre_filt_switch")
        self.apply_all_Inv_switch = QtWidgets.QCheckBox(self.remove_response_switch)
        self.apply_all_Inv_switch.setGeometry(QtCore.QRect(120, 130, 91, 21))
        self.apply_all_Inv_switch.setObjectName("apply_all_Inv_switch")
        self.f1_spin = QtWidgets.QDoubleSpinBox(self.remove_response_switch)
        self.f1_spin.setGeometry(QtCore.QRect(30, 70, 71, 22))
        self.f1_spin.setSpecialValueText("")
        self.f1_spin.setPrefix("")
        self.f1_spin.setDecimals(3)
        self.f1_spin.setMaximum(100.0)
        self.f1_spin.setSingleStep(0.001)
        self.f1_spin.setProperty("value", 0.0)
        self.f1_spin.setObjectName("f1_spin")
        self.f3_spin = QtWidgets.QDoubleSpinBox(self.remove_response_switch)
        self.f3_spin.setGeometry(QtCore.QRect(30, 100, 71, 22))
        self.f3_spin.setSpecialValueText("")
        self.f3_spin.setPrefix("")
        self.f3_spin.setDecimals(3)
        self.f3_spin.setMaximum(100.0)
        self.f3_spin.setProperty("value", 1.0)
        self.f3_spin.setObjectName("f3_spin")
        self.f2_spin = QtWidgets.QDoubleSpinBox(self.remove_response_switch)
        self.f2_spin.setGeometry(QtCore.QRect(130, 70, 71, 22))
        self.f2_spin.setSpecialValueText("")
        self.f2_spin.setPrefix("")
        self.f2_spin.setDecimals(3)
        self.f2_spin.setMaximum(100.0)
        self.f2_spin.setSingleStep(0.001)
        self.f2_spin.setProperty("value", 0.0)
        self.f2_spin.setObjectName("f2_spin")
        self.f4_spin = QtWidgets.QDoubleSpinBox(self.remove_response_switch)
        self.f4_spin.setGeometry(QtCore.QRect(130, 100, 71, 22))
        self.f4_spin.setSpecialValueText("")
        self.f4_spin.setPrefix("")
        self.f4_spin.setDecimals(3)
        self.f4_spin.setMaximum(100.0)
        self.f4_spin.setProperty("value", 1.0)
        self.f4_spin.setObjectName("f4_spin")
        self.label_7 = QtWidgets.QLabel(self.remove_response_switch)
        self.label_7.setGeometry(QtCore.QRect(10, 70, 16, 21))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.remove_response_switch)
        self.label_8.setGeometry(QtCore.QRect(110, 70, 16, 21))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.remove_response_switch)
        self.label_9.setGeometry(QtCore.QRect(10, 100, 16, 21))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.remove_response_switch)
        self.label_10.setGeometry(QtCore.QRect(110, 100, 16, 21))
        self.label_10.setObjectName("label_10")
        self.current_process = QtWidgets.QLabel(Dialog)
        self.current_process.setGeometry(QtCore.QRect(460, 30, 91, 17))
        self.current_process.setText("")
        self.current_process.setObjectName("current_process")
        self.lowpass_switch = QtWidgets.QGroupBox(Dialog)
        self.lowpass_switch.setGeometry(QtCore.QRect(340, 410, 211, 91))
        self.lowpass_switch.setCheckable(True)
        self.lowpass_switch.setChecked(False)
        self.lowpass_switch.setObjectName("lowpass_switch")
        self.frqspin = QtWidgets.QDoubleSpinBox(self.lowpass_switch)
        self.frqspin.setGeometry(QtCore.QRect(100, 30, 81, 22))
        self.frqspin.setSpecialValueText("")
        self.frqspin.setPrefix("")
        self.frqspin.setMaximum(100.0)
        self.frqspin.setProperty("value", 1.0)
        self.frqspin.setObjectName("frqspin")
        self.label_11 = QtWidgets.QLabel(self.lowpass_switch)
        self.label_11.setGeometry(QtCore.QRect(10, 30, 101, 21))
        self.label_11.setObjectName("label_11")
        self.lowpass_corners_spin = QtWidgets.QSpinBox(self.lowpass_switch)
        self.lowpass_corners_spin.setGeometry(QtCore.QRect(100, 60, 41, 22))
        self.lowpass_corners_spin.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lowpass_corners_spin.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.lowpass_corners_spin.setMinimum(2)
        self.lowpass_corners_spin.setMaximum(8)
        self.lowpass_corners_spin.setProperty("value", 4)
        self.lowpass_corners_spin.setObjectName("lowpass_corners_spin")
        self.label_12 = QtWidgets.QLabel(self.lowpass_switch)
        self.label_12.setGeometry(QtCore.QRect(30, 60, 54, 21))
        self.label_12.setObjectName("label_12")
        self.detrend_switch.raise_()
        self.File_list.raise_()
        self.channel_list.raise_()
        self.bandpass_switch.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.allchannel_checkbox.raise_()
        self.btnOK.raise_()
        self.btn_Cancel.raise_()
        self.remove_response_switch.raise_()
        self.current_process.raise_()
        self.lowpass_switch.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "预处理"))
        self.detrend_switch.setTitle(_translate("Dialog", "去倾"))
        self.radioLinear.setText(_translate("Dialog", "Linear型"))
        self.radioConstant.setText(_translate("Dialog", "Constant型"))
        self.bandpass_switch.setTitle(_translate("Dialog", "带通滤波"))
        self.fminspin.setSuffix(_translate("Dialog", " Hz"))
        self.fmaxspin.setSuffix(_translate("Dialog", " Hz"))
        self.label.setText(_translate("Dialog", "Lower Frequency"))
        self.label_2.setText(_translate("Dialog", "Upper Frequency"))
        self.label_5.setText(_translate("Dialog", "Corners"))
        self.label_3.setText(_translate("Dialog", "文件名"))
        self.label_4.setText(_translate("Dialog", "通道"))
        self.allchannel_checkbox.setText(_translate("Dialog", "所有通道"))
        self.btnOK.setText(_translate("Dialog", "确认"))
        self.btn_Cancel.setText(_translate("Dialog", "返回"))
        self.remove_response_switch.setTitle(_translate("Dialog", "去仪器响应"))
        self.label_6.setText(_translate("Dialog", "Water_level"))
        self.btn_setInv.setText(_translate("Dialog", "指定Inventory"))
        self.pre_filt_switch.setText(_translate("Dialog", "Pre_filt"))
        self.apply_all_Inv_switch.setText(_translate("Dialog", "应用全部"))
        self.f1_spin.setSuffix(_translate("Dialog", " Hz"))
        self.f3_spin.setSuffix(_translate("Dialog", " Hz"))
        self.f2_spin.setSuffix(_translate("Dialog", " Hz"))
        self.f4_spin.setSuffix(_translate("Dialog", " Hz"))
        self.label_7.setText(_translate("Dialog", "f1"))
        self.label_8.setText(_translate("Dialog", "f2"))
        self.label_9.setText(_translate("Dialog", "f3"))
        self.label_10.setText(_translate("Dialog", "f4"))
        self.lowpass_switch.setTitle(_translate("Dialog", "低通滤波"))
        self.frqspin.setSuffix(_translate("Dialog", " Hz"))
        self.label_11.setText(_translate("Dialog", "Frequency"))
        self.label_12.setText(_translate("Dialog", "Corners"))

