# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rcsui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1117, 868)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_2.sizePolicy().hasHeightForWidth())
        self.splitter_2.setSizePolicy(sizePolicy)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        self.splitter.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setMinimumSize(QtCore.QSize(256, 0))
        self.splitter.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.splitter.setFocusPolicy(QtCore.Qt.NoFocus)
        self.splitter.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.splitter.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.stationTree = QtWidgets.QTreeWidget(self.splitter)
        self.stationTree.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stationTree.sizePolicy().hasHeightForWidth())
        self.stationTree.setSizePolicy(sizePolicy)
        self.stationTree.setMaximumSize(QtCore.QSize(16777215, 600))
        self.stationTree.setFocusPolicy(QtCore.Qt.NoFocus)
        self.stationTree.setColumnCount(0)
        self.stationTree.setObjectName("stationTree")
        self.toolBox = QtWidgets.QToolBox(self.splitter)
        self.toolBox.setObjectName("toolBox")
        self.tools1 = QtWidgets.QWidget()
        self.tools1.setGeometry(QtCore.QRect(0, 0, 256, 257))
        self.tools1.setObjectName("tools1")
        self.ZButton = QtWidgets.QPushButton(self.tools1)
        self.ZButton.setGeometry(QtCore.QRect(0, 10, 61, 23))
        self.ZButton.setCheckable(True)
        self.ZButton.setChecked(True)
        self.ZButton.setObjectName("ZButton")
        self.NButton = QtWidgets.QPushButton(self.tools1)
        self.NButton.setGeometry(QtCore.QRect(90, 10, 61, 23))
        self.NButton.setCheckable(True)
        self.NButton.setChecked(False)
        self.NButton.setObjectName("NButton")
        self.EButton = QtWidgets.QPushButton(self.tools1)
        self.EButton.setGeometry(QtCore.QRect(180, 10, 61, 23))
        self.EButton.setCheckable(True)
        self.EButton.setChecked(False)
        self.EButton.setObjectName("EButton")
        self.btn_cursor = QtWidgets.QPushButton(self.tools1)
        self.btn_cursor.setGeometry(QtCore.QRect(0, 50, 97, 26))
        self.btn_cursor.setCheckable(True)
        self.btn_cursor.setChecked(True)
        self.btn_cursor.setObjectName("btn_cursor")
        self.AmpUP = QtWidgets.QPushButton(self.tools1)
        self.AmpUP.setGeometry(QtCore.QRect(0, 90, 97, 26))
        self.AmpUP.setObjectName("AmpUP")
        self.Ampdown = QtWidgets.QPushButton(self.tools1)
        self.Ampdown.setGeometry(QtCore.QRect(130, 90, 97, 26))
        self.Ampdown.setObjectName("Ampdown")
        self.toolBox.addItem(self.tools1, "")
        self.toos2 = QtWidgets.QWidget()
        self.toos2.setGeometry(QtCore.QRect(0, 0, 256, 257))
        self.toos2.setObjectName("toos2")
        self.toolBox.addItem(self.toos2, "")
        self.qmlcanvas = Qcwidget(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qmlcanvas.sizePolicy().hasHeightForWidth())
        self.qmlcanvas.setSizePolicy(sizePolicy)
        self.qmlcanvas.setObjectName("qmlcanvas")
        self.horizontalLayout.addWidget(self.splitter_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1117, 23))
        self.menubar.setObjectName("menubar")
        self.menuopen = QtWidgets.QMenu(self.menubar)
        self.menuopen.setObjectName("menuopen")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionopen = QtWidgets.QAction(MainWindow)
        self.actionopen.setObjectName("actionopen")
        self.actionexit = QtWidgets.QAction(MainWindow)
        self.actionexit.setObjectName("actionexit")
        self.menuopen.addAction(self.actionopen)
        self.menuopen.addAction(self.actionexit)
        self.menubar.addAction(self.menuopen.menuAction())

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        self.stationTree.itemDoubleClicked['QTreeWidgetItem*','int'].connect(MainWindow._changeStationVisibility)
        self.ZButton.clicked.connect(MainWindow._changeSelectedChannel)
        self.NButton.clicked.connect(MainWindow._changeSelectedChannel)
        self.EButton.clicked.connect(MainWindow._changeSelectedChannel)
        self.btn_cursor.clicked.connect(MainWindow._changebtn_cursor)
        self.AmpUP.clicked.connect(MainWindow._Ampup)
        self.Ampdown.clicked.connect(MainWindow._Ampdown)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ZButton.setText(_translate("MainWindow", "Z"))
        self.NButton.setText(_translate("MainWindow", "N"))
        self.EButton.setText(_translate("MainWindow", "E"))
        self.btn_cursor.setText(_translate("MainWindow", "辅助竖线"))
        self.AmpUP.setText(_translate("MainWindow", "放大振幅"))
        self.Ampdown.setText(_translate("MainWindow", "缩小振幅"))
        self.menuopen.setTitle(_translate("MainWindow", "文件"))
        self.actionopen.setText(_translate("MainWindow", "打开"))
        self.actionexit.setText(_translate("MainWindow", "退出"))

from util import Qcwidget
