# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rcsui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1117, 868)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setVerticalSpacing(1)
        self.gridLayout.setObjectName("gridLayout")
        self.AmpUP = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AmpUP.sizePolicy().hasHeightForWidth())
        self.AmpUP.setSizePolicy(sizePolicy)
        self.AmpUP.setMaximumSize(QtCore.QSize(30, 16777215))
        self.AmpUP.setObjectName("AmpUP")
        self.gridLayout.addWidget(self.AmpUP, 0, 5, 1, 1)
        self.ZCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ZCheckBox.sizePolicy().hasHeightForWidth())
        self.ZCheckBox.setSizePolicy(sizePolicy)
        self.ZCheckBox.setAutoFillBackground(False)
        self.ZCheckBox.setChecked(True)
        self.ZCheckBox.setObjectName("ZCheckBox")
        self.gridLayout.addWidget(self.ZCheckBox, 0, 2, 1, 1)
        self.current_time = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.current_time.sizePolicy().hasHeightForWidth())
        self.current_time.setSizePolicy(sizePolicy)
        self.current_time.setMinimumSize(QtCore.QSize(200, 0))
        self.current_time.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.current_time.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.current_time.setAlignment(QtCore.Qt.AlignCenter)
        self.current_time.setReadOnly(True)
        self.current_time.setClearButtonEnabled(False)
        self.current_time.setObjectName("current_time")
        self.gridLayout.addWidget(self.current_time, 0, 9, 1, 1)
        self.reset = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reset.sizePolicy().hasHeightForWidth())
        self.reset.setSizePolicy(sizePolicy)
        self.reset.setMaximumSize(QtCore.QSize(50, 16777215))
        self.reset.setObjectName("reset")
        self.gridLayout.addWidget(self.reset, 0, 6, 1, 1)
        self.NCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NCheckBox.sizePolicy().hasHeightForWidth())
        self.NCheckBox.setSizePolicy(sizePolicy)
        self.NCheckBox.setObjectName("NCheckBox")
        self.gridLayout.addWidget(self.NCheckBox, 0, 3, 1, 1)
        self.ECheckBox = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ECheckBox.sizePolicy().hasHeightForWidth())
        self.ECheckBox.setSizePolicy(sizePolicy)
        self.ECheckBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.ECheckBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ECheckBox.setAutoRepeatDelay(300)
        self.ECheckBox.setObjectName("ECheckBox")
        self.gridLayout.addWidget(self.ECheckBox, 0, 4, 1, 1)
        self.Ampdown = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Ampdown.sizePolicy().hasHeightForWidth())
        self.Ampdown.setSizePolicy(sizePolicy)
        self.Ampdown.setMaximumSize(QtCore.QSize(30, 16777215))
        self.Ampdown.setObjectName("Ampdown")
        self.gridLayout.addWidget(self.Ampdown, 0, 7, 1, 1)
        self.name_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_label.sizePolicy().hasHeightForWidth())
        self.name_label.setSizePolicy(sizePolicy)
        self.name_label.setMinimumSize(QtCore.QSize(140, 0))
        self.name_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.name_label.setFrameShape(QtWidgets.QFrame.Box)
        self.name_label.setTextFormat(QtCore.Qt.AutoText)
        self.name_label.setAlignment(QtCore.Qt.AlignCenter)
        self.name_label.setObjectName("name_label")
        self.gridLayout.addWidget(self.name_label, 0, 8, 1, 1)
        self.Amp_display = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Amp_display.sizePolicy().hasHeightForWidth())
        self.Amp_display.setSizePolicy(sizePolicy)
        self.Amp_display.setMaximumSize(QtCore.QSize(80, 16777215))
        self.Amp_display.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Amp_display.setAlignment(QtCore.Qt.AlignCenter)
        self.Amp_display.setReadOnly(True)
        self.Amp_display.setObjectName("Amp_display")
        self.gridLayout.addWidget(self.Amp_display, 0, 10, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 11, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 0, 1, 1)
        self.cursor_switch = QtWidgets.QCheckBox(self.centralwidget)
        self.cursor_switch.setObjectName("cursor_switch")
        self.gridLayout.addWidget(self.cursor_switch, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_2.sizePolicy().hasHeightForWidth())
        self.splitter_2.setSizePolicy(sizePolicy)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        self.splitter.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setMinimumSize(QtCore.QSize(256, 0))
        self.splitter.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.splitter.setFocusPolicy(QtCore.Qt.NoFocus)
        self.splitter.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.splitter.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.stationTree = QtWidgets.QTreeWidget(self.splitter)
        self.stationTree.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stationTree.sizePolicy().hasHeightForWidth())
        self.stationTree.setSizePolicy(sizePolicy)
        self.stationTree.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.stationTree.setFocusPolicy(QtCore.Qt.NoFocus)
        self.stationTree.setColumnCount(0)
        self.stationTree.setObjectName("stationTree")
        self.qmlcanvas = Qcwidget(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qmlcanvas.sizePolicy().hasHeightForWidth())
        self.qmlcanvas.setSizePolicy(sizePolicy)
        self.qmlcanvas.setObjectName("qmlcanvas")
        self.verticalLayout.addWidget(self.splitter_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1117, 23))
        self.menubar.setObjectName("menubar")
        self.menuopen = QtWidgets.QMenu(self.menubar)
        self.menuopen.setObjectName("menuopen")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionopen = QtWidgets.QAction(MainWindow)
        self.actionopen.setObjectName("actionopen")
        self.actionexit = QtWidgets.QAction(MainWindow)
        self.actionexit.setObjectName("actionexit")
        self.menuopen.addAction(self.actionopen)
        self.menuopen.addAction(self.actionexit)
        self.menubar.addAction(self.menuopen.menuAction())

        self.retranslateUi(MainWindow)
        self.stationTree.itemDoubleClicked['QTreeWidgetItem*','int'].connect(MainWindow._changeStationVisibility)
        self.cursor_switch.clicked.connect(MainWindow._changebtn_cursor)
        self.ECheckBox.stateChanged['int'].connect(MainWindow._changeSelectedChannel)
        self.NCheckBox.stateChanged['int'].connect(MainWindow._changeSelectedChannel)
        self.AmpUP.clicked.connect(MainWindow._Ampup)
        self.Ampdown.clicked.connect(MainWindow._Ampdown)
        self.reset.clicked.connect(MainWindow._AmpReset)
        self.ZCheckBox.stateChanged['int'].connect(MainWindow._changeSelectedChannel)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.AmpUP.setText(_translate("MainWindow", "△"))
        self.ZCheckBox.setText(_translate("MainWindow", "Z"))
        self.current_time.setText(_translate("MainWindow", "YY-MM-DD hh-mm-ss.SSS"))
        self.reset.setText(_translate("MainWindow", "Reset"))
        self.NCheckBox.setText(_translate("MainWindow", "N"))
        self.ECheckBox.setText(_translate("MainWindow", "E"))
        self.Ampdown.setText(_translate("MainWindow", "▽"))
        self.name_label.setText(_translate("MainWindow", " "))
        self.Amp_display.setText(_translate("MainWindow", "μm/s"))
        self.cursor_switch.setText(_translate("MainWindow", "光标"))
        self.menuopen.setTitle(_translate("MainWindow", "文件"))
        self.actionopen.setText(_translate("MainWindow", "打开"))
        self.actionexit.setText(_translate("MainWindow", "退出"))

from util import Qcwidget
